name: Delete Auto Upload Screenshots
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  delete-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 删除目标图片
        run: |
          rm -f 已完结_*.png
          rm -f 进行中_*.png

      - name: 提交更改
        uses: EndBug/add-and-commit@v9
        with:
          message: "安全清理：仅删除自动上传截图"
